### ISSUE TITLE
How to creat frames?

### ISSUE THREAD

**Issue by a5552033** [NTIA/gr-ltetrigger#6]
@djanderson 
I am sorry for @ you and I want to ask you some questions about the project.I want to know how to get the LTE  frame like ../test_frames/lte_frame_50prb_cellid_125?
Hope your reply!
Peggy

**Comment by djanderson** [comment]
Hi Peggy,

I don't have the exact command on hand but I used srsLTE's `examples/pdsch_enodeb` utility. There are several examples of how to create different types of output in their README: https://github.com/srsLTE/srsLTE.

**Comment by a5552033** [comment]
OK,thank u for your answers.But I have found the project srsLTE just support USRP & BladeRF:-(

**Comment by djanderson** [comment]
There is an option to dump the samples to a file instead of to a radio
(check the `--help` menu of the example).
